name: secrets
description: "Local secrets storage"
version: 1.2.0+2

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  loading_indicator: ^3.1.1
  path_provider: ^2.1.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  crypto: ^3.0.5
  encrypt: ^5.0.3
  pin_keyboard: ^1.1.2
  spoiler_widget: ^1.0.4
  package_info_plus: ^8.0.2
  flutter_zxing: ^2.0.0
  barcode: ^2.2.9
  flutter_svg: ^2.0.9
  camera: ^0.10.5+9
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: any
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  fonts:
    - family: Anonymous Pro
      fonts:
        - asset: assets/font/AnonymousPro-Bold.ttf
          weight: 800
        - asset: assets/font/AnonymousPro-Italic.ttf
          style: italic
        - asset: assets/font/AnonymousPro-Regular.ttf


