name: secrets
description: "Local secrets storage"
version: 1.0.0+1
isar_version: &isar_version 3.1.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  loading_indicator: ^3.1.1
  path_provider: ^2.1.4
  isar: *isar_version
  isar_flutter_libs: *isar_version
  crypto: ^3.0.5
  encrypt: ^5.0.3
  pin_keyboard: ^1.1.2
  spoiler_widget: ^1.0.4
  numberpicker: ^2.1.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: *isar_version
  build_runner: any
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher/res/mipmap-xxxhdpi/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  fonts:
    - family: Anonymous Pro
      fonts:
        - asset: assets/font/AnonymousPro-Bold.ttf
          weight: 800
        - asset: assets/font/AnonymousPro-Italic.ttf
          style: italic
        - asset: assets/font/AnonymousPro-Regular.ttf


