name: secrets
description: "Local secrets storage"
version: 1.0.0+1
isar_version: &isar_version 3.1.0+1 # define the version to be used

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  logger: ^2.4.0
  loading_indicator: ^3.1.1
  pinput: ^5.0.0
  path_provider: ^2.1.4
  isar: *isar_version
  isar_flutter_libs: *isar_version
  crypto: ^3.0.5
  encrypt: ^5.0.3
  pin_keyboard: ^1.1.2
  spoiler_widget: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: *isar_version
  build_runner: any

flutter:
  uses-material-design: true

